### ISSUE TITLE
Cannot install with version 3.1.2 of vmware-fusion plugin

### ISSUE THREAD

**Issue by kelbyers** [scalefactory/vagrant-multiprovider-snap#18]
This doesn't appear to work with the current version of the vagrant-vmware-fusion plugin:

    kels-mbp:~ jxb2016$ vagrant plugin list
    vagrant-vmware-fusion (3.1.2)
    kels-mbp:~ jxb2016$ vagrant plugin install vagrant-multiprovider-snap
    Installing the 'vagrant-multiprovider-snap' plugin. This can take a few minutes...
    Bundler, the underlying system Vagrant uses to install plugins,
    reported an error. The error is shown below. These errors are usually
    caused by misconfigured plugin installations or transient network
    issues. The error from Bundler is:

    Net::HTTPNotFound: No gems found matching "vagrant-vmware-fusion" "3.0.0" nil

**Comment by jtopper** [comment]
Hi Kel,

I haven't been able to reproduce this.  Can you show me the output from `vagrant version` and `vagrant plugin list`?  Which operating system are you running on?

**Comment by kelbyers** [comment]
Hi Jon,

I am running on Mac OS X, 10.9.5. 

In trying to recreate this along with the commands you requested, I have successfully installed this plugin. I'm not sure what the issue was, as I had rebooted the system multiple times with the current version of vagrant and the current versions of my plugins before I tried this a few days ago. The only thing that was different was that I had recently uninstalled vagrant-openstack and installled vagrant-openstack-provider in its place. I have rebooted my laptop since then.

Thanks for the response.

**Comment by jtopper** [comment]
Thanks Kel, I think we can put this one down to "one of those things".  vagrant-multiprovider-snap doesn't express any kind of gem metadata dependency on vagrant-vmware-fusion so that it can still be installed by users who don't use the VMWare plugin. I can't think of any way that this plugin would cause the error message you saw.
