### ISSUE TITLE
Intermittent issue taking snapshots in a multi-vm environment

### ISSUE THREAD

**Issue by davebirch** [scalefactory/vagrant-multiprovider-snap#19]
I'm currently seeing an odd issue with a multi-vm vagrant environment that I use for automated tests. The environment contains 5 machines, 1 master with a significantly different configuration and 4 minions which are initially configured the same (aside from obvious hostname & ip differences) but eventually have different services installed. These VMs are named "master" and "minion1" - "minion4"

I'm finding that roughly 10-20% of the time when I take a snapshot using the command:
vagrant snap take --name <snapshot> 
to snapshot the entire cluster, on restoring the snapshots, my "minion2" snapshots all seem to be snapshots of the "minion1" VM, which is causing me no end of issues.

I have tried to work around this issue by taking individual snapshots of the VMs, but see the same issue, oddly, always with the same "minion2" VM snapshots containing the saved state of "minion1".

The identifier I have been using to check this issue is the hostname of the box after the snapshots are restored. I can confirm from my testing that the hostname for minion2 remains as "minion2" until the first snapshot is restored so I don't think it's any issue with my test code.

Any ideas what could be causing this?

**Comment by jtopper** [comment]
Hi Dave! That sounds like a weird one.  Which VM provider are you using for these machines?

**Comment by davebirch** [comment]
Using Virtualbox

**Comment by jtopper** [comment]
I should probably also ask: what operating system are you using; and which version of Vagrant? Are you on the latest version of vagrant-multiprovider-snap (0.0.14)?

**Comment by davebirch** [comment]
Sorry, I had stopped using vagrant-multiprovider-snap in favour of vagrant-vbox-snapshot as it seemed not to suffer from this issue. To answer your questions, I'm on Ubuntu 14.04, at the time this was raised I was using Vagrant 1.6.3 and the latest version of your plugin.

I'll try and put some proper steps to reproduce together for you when I get a moment.

**Comment by jtopper** [comment]
Thanks Dave, I haven't been able to reproduce this myself, so any steps you can provide will be useful.

**Comment by jtopper** [comment]
I'm going to close this for now. Please feel free to reopen the issue if you're able to add repro steps.
