### ISSUE TITLE
Support docker provider

### ISSUE THREAD

**Issue by tknerr** [scalefactory/vagrant-multiprovider-snap#20]
Docker support would be awesome! :-)

**Comment by jtopper** [comment]
I haven't use Vagrant with the docker provider - can you describe your setup in a bit more detail, and I'll see what we can do with it?

**Comment by cantbefound** [comment]
Log in

**Comment by cantbefound** [comment]
Log in

**Comment by jtopper** [comment]
As per #21 I'm going to discontinue this plugin once Vagrant core is at feature parity, so I'm afraid this plugin won't be getting support for Docker.
