### ISSUE TITLE
Deprecate this plugin when there's parity with Vagrant core support

### ISSUE THREAD

**Issue by jtopper** [scalefactory/vagrant-multiprovider-snap#21]
As of Vagrant 1.8, the vagrant core provides snapshot commands (https://docs.vagrantup.com/v2/cli/snapshot.html).  Whilst you can install vagrant-multiprovider-snap alongside Vagrant (the commands are different), **I will be deprecating this plugin when the issues below are resolved with Vagrant core**
### Command-Line Usage

There are a handful of differences in behaviour with the new Vagrant snapshot command, making it tricky to migrate directly from this plugin.  I've raised pull requests against Vagrant to resolve these which I hope are uncontroversial enough to be merged in a future release.

| This plugin | Vagrant core | Current Issues | Fix PR |
| --- | --- | --- | --- |
| `vagrant snap take` | `vagrant snapshot push` | n/a | n/a |
| `vagrant snap rollback` | `vagrant snapshot pop` | Old snapshot deleted. Provisioners run after rollback. | [vagrant/#6879](https://github.com/mitchellh/vagrant/pull/6879): Proposed `--no-delete` and `--no-provision` flags |
| `vagrant snap take [vm-name] --name=<snapname>` | `vagrant snapshot save [vm-name] <snapname>` | n/a | n/a |
| `vagrant snap rollback [vm-name] --name=<snapname>` | `vagrant snapshot restore [vm-name] <snapname>` | Provisioners run after rollback. | [vagrant/#6879](https://github.com/mitchellh/vagrant/pull/6879): Proposed `--no-provision` flags |
### Provider Support

At present, Vagrant core doesn't support all the providers supported by this plugin.

| Provider | This plugin | Vagrant core | PR |
| --- | --- | --- | --- |
| VirtualBox | :heavy_check_mark: | :heavy_check_mark: | n/a |
| VMWare | :heavy_check_mark: | :heavy_check_mark:  (with commercial plugin) | n/a |
| HyperV | :heavy_check_mark: | ✔️ | https://github.com/mitchellh/vagrant/pull/7110 |

**Comment by jtopper** [comment]
At the time of writing, HEAD of Vagrant core now supports everything this plugin supports.  When the next Vagrant release is made available, this plugin will generate deprecation warnings, and will no longer be supported.

**Comment by scaleoutsean** [comment]
There's a note[1] saying it's integrated, but the plugin itself hasn't been moved to Deprecated section. I could edit the Wiki page, but it should probably be done by plugin author.

[1] https://github.com/hashicorp/vagrant/wiki/Available-Vagrant-Plugins#snapshots

**Comment by jtopper** [comment]
Thanks for the reminder @scaleoutsean! I've updated the wiki page and will push a new plugin shortly with deprecation warnings.

**Comment by jtopper** [comment]
New 0.0.15 released, now with deprecation warnings.

**Comment by StefanScherer** [comment]
😢, but consequent. So now I have a real reason to learn the slight more complex built-in commands ;-)
Thanks for this plugin, it helped me for several years with its short and precise commands that stick in the brain.
