### ISSUE TITLE
Command to delete all snapshots

### ISSUE THREAD

**Issue by MoeweX** [scalefactory/vagrant-multiprovider-snap#22]
In the command [directory](https://github.com/scalefactory/vagrant-multiprovider-snap/tree/master/lib/vagrant-multiprovider-snap/command), I cannot find a script to delete all snapshots for clean up. Does the plugin already provide such a functionality or do you plan to add it?

**Comment by jtopper** [comment]
Hi, I don't intend to add such a feature. Now that Hashicorp have added native snapshot support to Vagrant itself, I'm not really going to be doing any further work on this plugin.

**Comment by MoeweX** [comment]
Hi, I did not notice that they added such a functionality, that works for me as well. Thanks for now :)
